import os
import json
import re
import datetime
import traceback
import urllib.request
import urllib.parse

try:
    import google.generativeai as genai
    has_gemini = True
except ImportError:
    has_gemini = False

try:
    import groq
    has_groq = True
except ImportError:
    has_groq = False

from dotenv import load_dotenv

load_dotenv()

def send_telegram_message(text):
    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    if not token or not chat_id:
        print("Telegram credentials missing, skipping notification.")
        return
    
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    data = urllib.parse.urlencode({"chat_id": chat_id, "text": text, "parse_mode": "Markdown"}).encode("utf-8")
    try:
        req = urllib.request.Request(url, data=data)
        with urllib.request.urlopen(req) as response:
            res = response.read()
            print("Telegram message sent successfully.")
    except Exception as e:
        print(f"Failed to send Telegram message: {e}")

def call_llm(prompt):
    gemini_key = os.environ.get("GEMINI_API_KEY")
    groq_key = os.environ.get("GROQ_API_KEY")

    if has_gemini and gemini_key and gemini_key != "your_gemini_api_key_here":
        try:
            genai.configure(api_key=gemini_key)
            model = genai.GenerativeModel("gemini-1.5-flash")
            response = model.generate_content(prompt)
            return response.text
        except Exception as e:
            print(f"Gemini failed: {e}. Falling back to Groq...")

    if has_groq and groq_key and groq_key != "your_groq_api_key_here":
        try:
            client = groq.Groq(api_key=groq_key)
            chat_completion = client.chat.completions.create(
                messages=[{"role": "user", "content": prompt}],
                model="llama3-70b-8192",
            )
            return chat_completion.choices[0].message.content
        except Exception as e:
            print(f"Groq failed: {e}")
            raise Exception("Both Gemini and Groq failed or keys are missing.")

    raise Exception("No valid API keys found for Gemini or Groq.")

def load_data():
    with open("data/watchlist.json", "r", encoding="utf-8") as f:
        watchlist = json.load(f)
    
    with open("data/prices.json", "r", encoding="utf-8") as f:
        prices = json.load(f)["prices"]
        
    try:
        with open("data/research_log.json", "r", encoding="utf-8") as f:
            logs = json.load(f)
    except Exception:
        logs = {}
        
    try:
        with open("data/budget.json", "r", encoding="utf-8") as f:
            budget = json.load(f)
    except Exception:
        budget = {"monthly_budget": 8000, "carry_forward": 0}
        
    with open("frontend/src/data/fundamentals.js", "r", encoding="utf-8") as f:
        f_text = f.read()
    
    match = re.search(r'export const FUNDAMENTALS = (\{.*?\});', f_text, re.DOTALL)
    obj_str = match.group(1) if match else "No fundamentals found."

    return watchlist, prices, logs, budget, obj_str

def generate_report():
    watchlist, prices, logs, budget, fundamentals_str = load_data()
    total_budget = budget.get("monthly_budget", 8000) + budget.get("carry_forward", 0)
    
    markdown_report = f"# SIP Portfolio AI Monthly Report - {datetime.date.today().strftime('%B %Y')}\n\n"
    markdown_report += f"**Total Budget Available:** ৳{total_budget}\n\n"
    markdown_report += "*Generated by Multi-Agent AI Pipeline (Warren Buffett Style Value Investing)*\n\n"

    # We will first analyze each stock to get a score and summary, then make a final allocation
    analyses = []
    
    for ticker in watchlist:
        ltp = prices.get(ticker, {}).get("LTP", "Unknown")
        
        # Compile all recent news for this ticker
        ticker_news = []
        for date_str, daily_logs in logs.items():
            if ticker in daily_logs:
                ticker_news.append(f"[{date_str}]: {daily_logs[ticker]}")
        compiled_news = "\n".join(ticker_news) if ticker_news else "No recent news."
        
        prompt = f"""
You are a rigorous, Warren Buffett-style value investor analyzing {ticker} on the Dhaka Stock Exchange.
You prioritize strong fundamentals (High ROE, low Debt/Equity, consistent EPS growth) at 90%, and technical momentum at 10%.

LTP: {ltp}
Compiled News over the month:
{compiled_news}

Fundamentals Database Snippet:
{fundamentals_str}

Evaluate this stock. Output strictly in JSON format:
{{
  "convictionScore": <0 to 100 integer>,
  "buffettReasoning": "1-2 paragraph rigorous fundamental analysis",
  "buyPriceLimit": <max price to pay, float>
}}
"""
        print(f"Analyzing {ticker}...")
        try:
            resp_text = call_llm(prompt).replace('```json', '').replace('```', '').strip()
            data = json.loads(resp_text)
            analyses.append({
                "ticker": ticker,
                "ltp": ltp,
                "score": data["convictionScore"],
                "reason": data["buffettReasoning"],
                "limit": data["buyPriceLimit"]
            })
            
            markdown_report += f"## {ticker} (Conviction: {data['convictionScore']}/100)\n"
            markdown_report += f"**LTP:** {ltp} | **Max Buy Limit:** {data['buyPriceLimit']}\n\n"
            markdown_report += f"> {data['buffettReasoning']}\n\n"
            
        except Exception as e:
            print(f"Error analyzing {ticker}: {e}")

    # Now, the Debater / Orchestrator allocates the budget
    analyses.sort(key=lambda x: x["score"], reverse=True)
    
    allocation_prompt = f"""
You are the Chief Investment Officer. 
You have a total budget of ৳{total_budget} to invest this month.
Here are the top analyzed stocks, ranked by conviction score:
{json.dumps(analyses, indent=2)}

Decide EXACTLY how many shares of which stocks to buy this month to maximize long-term compounding, keeping total cost under ৳{total_budget}. You do NOT have to spend the whole budget if prices are too high above limits. Unspent money becomes carry forward.

Output strictly in JSON format:
{{
  "allocations": [
    {{"ticker": "TICKER", "qty": 10, "price": 250, "total": 2500}}
  ],
  "totalSpent": 2500,
  "carryForward": 5500,
  "summary": "Short 2 sentence reasoning for this allocation."
}}
"""
    print("Allocating budget...")
    try:
        resp_text = call_llm(allocation_prompt).replace('```json', '').replace('```', '').strip()
        final_alloc = json.loads(resp_text)
        
        markdown_report = f"# Final Allocation\n\n> {final_alloc['summary']}\n\n" + markdown_report
        markdown_report += "\n### Purchases:\n"
        for item in final_alloc['allocations']:
            markdown_report += f"- **{item['ticker']}**: {item['qty']} shares @ ৳{item['price']} = ৳{item['total']}\n"
        markdown_report += f"\n**Total Spent:** ৳{final_alloc['totalSpent']}\n"
        markdown_report += f"**New Carry Forward:** ৳{final_alloc['carryForward']}\n"
        
        # update budget.json
        budget["carry_forward"] = final_alloc["carryForward"]
        with open("data/budget.json", "w", encoding="utf-8") as f:
            json.dump(budget, f, indent=2)
            
        # Send Telegram notification
        telegram_text = f"📈 *Buffett-AI Monthly Allocation*\n\n"
        for item in final_alloc['allocations']:
            telegram_text += f"- {item['ticker']}: {item['qty']} shares @ ৳{item['price']} (৳{item['total']})\n"
        telegram_text += f"\n💰 *Total Spent:* ৳{final_alloc['totalSpent']}\n"
        telegram_text += f"💼 *Carry Forward:* ৳{final_alloc['carryForward']}\n"
        telegram_text += f"📝 *Reasoning:* {final_alloc['summary']}\n\n[View Full Report](https://github.com/ikraaaaam/bd-multibagger-data/blob/main/data/latest_picks.md)"
        
        send_telegram_message(telegram_text)
        
    except Exception as e:
        print(f"Error in allocation phase: {e}")
        
    with open("data/latest_picks.md", "w", encoding="utf-8") as f:
        f.write(markdown_report)
        
    # We still need to write latest_picks.json for the frontend (just a simple mock structure so it doesn't break)
    frontend_json = []
    for a in analyses:
        is_picked = False
        for alloc in final_alloc.get("allocations", []):
            if alloc["ticker"] == a["ticker"]:
                is_picked = True
        
        frontend_json.append({
            "ticker": a["ticker"],
            "pick": is_picked,
            "recommendation": "PICK" if is_picked else "SKIP",
            "totalScore": a["score"],
            "ltp": a["ltp"],
            "orchestratorReason": a["reason"],
            "agents": []
        })
        
    with open("data/latest_picks.json", "w", encoding="utf-8") as f:
        json.dump(frontend_json, f, indent=2)

if __name__ == "__main__":
    generate_report()
