import os
import json
import re
import datetime
import urllib.request
import traceback
try:
    from duckduckgo_search import DDGS
    has_ddgs = True
except ImportError:
    has_ddgs = False

try:
    import google.generativeai as genai
    has_gemini = True
except ImportError:
    has_gemini = False

try:
    import groq
    has_groq = True
except ImportError:
    has_groq = False

from dotenv import load_dotenv

load_dotenv()

def fetch_news(ticker):
    print(f"Fetching news for {ticker}...")
    if not has_ddgs:
        return "News fetching skipped (duckduckgo_search not installed)."
    try:
        results = DDGS().text(f"{ticker} stock news Bangladesh OR Dhaka Stock Exchange", max_results=3)
        if not results:
            return "No recent news found."
        news_text = ""
        for r in results:
            news_text += f"- {r.get('title')}: {r.get('body')}\n"
        return news_text
    except Exception as e:
        return f"Error fetching news: {e}"

def load_data():
    with open("data/watchlist.json", "r", encoding="utf-8") as f:
        watchlist = json.load(f)
    
    with open("data/prices.json", "r", encoding="utf-8") as f:
        prices = json.load(f)["prices"]
        
    # Read fundamentals.js (regex parse)
    with open("frontend/src/data/fundamentals.js", "r", encoding="utf-8") as f:
        f_text = f.read()
    
    fundamentals = {}
    # Simple regex to extract JSON-like object
    match = re.search(r'export const FUNDAMENTALS = (\{.*?\});', f_text, re.DOTALL)
    if match:
        obj_str = match.group(1)
        # It's JS, not strict JSON. Let's just use it as string context for the LLM
        # The LLM is smart enough to read JS.
    else:
        obj_str = "No fundamentals found."

    return watchlist, prices, obj_str

def call_llm(prompt):
    gemini_key = os.environ.get("GEMINI_API_KEY")
    groq_key = os.environ.get("GROQ_API_KEY")

    if has_gemini and gemini_key and gemini_key != "your_gemini_api_key_here":
        try:
            genai.configure(api_key=gemini_key)
            model = genai.GenerativeModel("gemini-1.5-flash")
            response = model.generate_content(prompt)
            return response.text
        except Exception as e:
            print(f"Gemini failed: {e}. Falling back to Groq...")

    if has_groq and groq_key and groq_key != "your_groq_api_key_here":
        try:
            client = groq.Groq(api_key=groq_key)
            chat_completion = client.chat.completions.create(
                messages=[{"role": "user", "content": prompt}],
                model="llama3-70b-8192",
            )
            return chat_completion.choices[0].message.content
        except Exception as e:
            print(f"Groq failed: {e}")
            raise Exception("Both Gemini and Groq failed or keys are missing.")

    raise Exception("No valid API keys found for Gemini or Groq.")

def generate_report(watchlist, prices, fundamentals_str):

    results_json = []
    markdown_report = f"# SIP Portfolio AI Monthly Report - {datetime.date.today().strftime('%B %Y')}\n\n"
    markdown_report += "*Generated by Multi-Agent AI Pipeline (Technical, Research, Risk, News, and Orchestrator)*\n\n"

    for ticker in watchlist:
        news = fetch_news(ticker)
        ltp = prices.get(ticker, {}).get("LTP", "Unknown")
        ycp = prices.get(ticker, {}).get("YCP", "Unknown")
        change_pct = "Unknown"
        if ltp != "Unknown" and ycp != "Unknown" and ycp > 0:
            change_pct = round(((ltp - ycp) / ycp) * 100, 2)

        prompt = f"""
You are an expert AI orchestrator for a stock portfolio on the Dhaka Stock Exchange (DSE).
You are analyzing the ticker: {ticker}.

CONTEXT:
LTP (Last Traded Price): {ltp}
Change vs Yesterday: {change_pct}%
News Summary:
{news}

Fundamentals Database Snippet (JS format):
{fundamentals_str}

TASKS:
1. Research Agent: Evaluate the fundamental health of {ticker} from the provided database snippet.
2. Technical Agent: Evaluate the current price and momentum.
3. Risk Agent: Evaluate the broader context of adding this to a monthly SIP.
4. Orchestrator: Synthesize the findings and make a definitive decision for this month: "PICK", "HOLD", or "SKIP".

OUTPUT FORMAT:
Respond EXACTLY in this JSON format, no extra markdown around it:
{{
  "recommendation": "PICK/HOLD/SKIP",
  "totalScore": <integer from 1 to 15 based on conviction>,
  "orchestratorReason": "A 1-2 sentence compelling summary of why this is the decision.",
  "researchNotes": "Bullet points from Research Agent",
  "techNotes": "Bullet points from Technical Agent",
  "riskNotes": "Bullet points from Risk Agent",
  "newsNotes": "Summary of news relevance"
}}
"""
        print(f"Running LLM analysis for {ticker}...")
        try:
            response_text = call_llm(prompt)
            # clean up markdown if any
            resp_text = response_text.replace('```json', '').replace('```', '').strip()
            data = json.loads(resp_text)
            
            # Save to JSON array for frontend
            results_json.append({
                "ticker": ticker,
                "pick": data["recommendation"] == "PICK",
                "recommendation": data["recommendation"],
                "totalScore": data["totalScore"],
                "ltp": ltp,
                "orchestratorReason": data["orchestratorReason"],
                "agents": [
                    {"agent": "Research Agent", "points": 0, "reasons": [data["researchNotes"]]},
                    {"agent": "Technical Agent", "points": 0, "reasons": [data["techNotes"]]},
                    {"agent": "Risk Agent", "points": 0, "reasons": [data["riskNotes"]]},
                    {"agent": "News Agent", "points": 0, "reasons": [data["newsNotes"]]},
                ]
            })

            # Append to Markdown report
            markdown_report += f"## {ticker} - {data['recommendation']} (Score: {data['totalScore']})\n"
            markdown_report += f"**LTP:** {ltp} | **Change:** {change_pct}%\n\n"
            markdown_report += f"> {data['orchestratorReason']}\n\n"
            markdown_report += f"### News\n{data['newsNotes']}\n\n"
            markdown_report += f"### Fundamentals\n{data['researchNotes']}\n\n"
            markdown_report += f"### Technicals\n{data['techNotes']}\n\n"
            markdown_report += f"### Risk\n{data['riskNotes']}\n\n"
            markdown_report += "---\n\n"

        except Exception as e:
            print(f"Error processing {ticker}: {e}")
            traceback.print_exc()

    # Save outputs
    with open("data/latest_picks.json", "w", encoding="utf-8") as f:
        json.dump(results_json, f, indent=2)
    
    report_name = f"data/latest_picks.md"
    with open(report_name, "w", encoding="utf-8") as f:
        f.write(markdown_report)

    print(f"Done! Saved outputs to {report_name} and data/latest_picks.json")

if __name__ == "__main__":
    w, p, f = load_data()
    generate_report(w, p, f)
