import React, { useState, useEffect } from 'react';
import { Bot, RefreshCw, AlertTriangle, Activity, Search, ShieldAlert, Newspaper } from 'lucide-react';
import { getAIInsight } from '../services/aiAgent';

export default function AIPanel({ ticker, fundamentalData, technicalData }) {
  const [activeTab, setActiveTab] = useState('research');
  const [loading, setLoading] = useState(false);
  const [insight, setInsight] = useState(null);

  useEffect(() => {
    let active = true;
    
    async function fetchInsight() {
      setLoading(true);
      try {
        const result = await getAIInsight(ticker, activeTab, fundamentalData, technicalData);
        if (active) setInsight(result);
      } catch (e) {
        console.error("AI fetch error:", e);
        if (active) setInsight({ text: "Error communicating with AI.", agent: "System" });
      } finally {
        if (active) setLoading(false);
      }
    }
    
    fetchInsight();
    return () => { active = false; };
  }, [ticker, activeTab, fundamentalData, technicalData]);

  const tabs = [
    { id: 'news', label: 'News', icon: Newspaper },
    { id: 'research', label: 'Research', icon: Search },
    { id: 'technical', label: 'Technical', icon: Activity },
    { id: 'risk', label: 'Risk', icon: ShieldAlert }
  ];

  return (
    <div className="bg-[#121a16] border border-[#22302a] rounded-xl overflow-hidden mt-6 shadow-lg">
      <div className="bg-[#1a2420] border-b border-[#22302a] px-4 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Bot className="text-[#c9a24b]" size={20} />
          <h3 className="font-bold text-white tracking-wider uppercase text-sm">Multi-Agent AI Analysis</h3>
        </div>
        <div className="flex gap-2">
          {tabs.map(tab => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                  isActive ? 'bg-[#1fae6b22] text-[#2fd888] border border-[#1fae6b44]' : 'text-[#7d8a83] hover:text-[#e9ede8] hover:bg-[#22302a]'
                }`}
              >
                <Icon size={14} /> {tab.label}
              </button>
            )
          })}
        </div>
      </div>

      <div className="p-5 min-h-[120px] relative">
        {loading ? (
          <div className="flex flex-col items-center justify-center text-[#5f6b65] h-full py-6">
            <RefreshCw className="animate-spin mb-2" size={24} />
            <span className="text-sm font-['IBM_Plex_Mono'] font-bold uppercase tracking-widest">
              Consulting {tabs.find(t => t.id === activeTab).label} Agent...
            </span>
          </div>
        ) : insight ? (
          <div className="animate-in fade-in duration-300">
            <div className="text-[11px] font-bold text-[#c9a24b] uppercase tracking-widest mb-2 flex items-center gap-1.5">
              <Bot size={12} /> {insight.agent}
            </div>
            <p className="text-[#e9ede8] leading-relaxed font-['IBM_Plex_Sans'] text-[15px]">
              {insight.text}
            </p>
          </div>
        ) : null}
      </div>
      
      <div className="bg-[#0a0f0c] border-t border-[#22302a] px-4 py-2 flex items-center justify-between text-[#5f6b65] text-[11px] uppercase tracking-wider font-bold">
        <div className="flex items-center gap-1.5 text-[#c9a24b] opacity-80">
          <AlertTriangle size={12} /> Not Financial Advice. Verify Independently.
        </div>
        <div>Generated by Mock Claude AI</div>
      </div>
    </div>
  );
}
